"""
Settings for the application.
"""
import os
from dotenv import load_dotenv

load_dotenv()

SHORT_TERM_MEMORY_LIMIT = int(os.getenv("SHORT_TERM_MEMORY_LIMIT", "10"))
LONG_TERM_MEMORY_INTERVAL = max(
    1,
    int(os.getenv("LONG_TERM_MEMORY_INTERVAL", str(SHORT_TERM_MEMORY_LIMIT))),
)
MAX_TOKENS = int(os.getenv("MAX_TOKENS", "4000"))
LONG_CONTEXT_MATCH_LIMIT = int(os.getenv("LONG_CONTEXT_MATCH_LIMIT", "5"))
RECENT_HISTORY_TURNS = max(5, int(os.getenv("RECENT_HISTORY_TURNS", "5")))

SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_KEY")
WEATHER_KEY = os.getenv("WEATHERSTACK_KEY")
ALPHA_KEY = os.getenv("ALPHA_VANTAGE_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")
SUPABASE_URL = os.getenv("SUPABASE_URL")
RAG_MAX_PAGES_LIMIT = os.getenv("RAG_MAX_PAGES_LIMIT")
TEXT_SPLITTER_CHUNK_SIZE = os.getenv("TEXT_SPLITTER_CHUNK_SIZE")
TEXT_SPLITTER_OVERLAP = os.getenv("TEXT_SPLITTER_OVERLAP")
